# Generated by Django 5.0.4 on 2024-04-17 17:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIstore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.CharField(max_length=100)),
                ("genre_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Friends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friend_name", models.CharField(max_length=100)),
                ("friend_username", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                ("friend_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_genre_id", models.IntegerField(unique=True)),
                ("genre_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Moviepreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                (
                    "preference",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="Y", max_length=3
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField(default=datetime.date.today)),
                (
                    "username",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Films",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("lang", models.CharField(default="en", max_length=20)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "poster_image",
                    models.URLField(
                        default="https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg"
                    ),
                ),
                ("genres", models.ManyToManyField(to="filmsearch.genre")),
            ],
        ),
    ]
