# Generated by Django 3.2.25 on 2024-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsearch', '0002_auto_20240407_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='poster_image',
            field=models.TextField(null=True),
        ),
    ]
