# Generated by Django 5.0.4 on 2024-04-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsearch', '0003_films_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='poster_image',
            field=models.URLField(null=True),
        ),
    ]
